version: "3.4"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    profiles: ["dev"]
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - "SA_PASSWORD=Admin1234!"
    volumes:
      - sql:/var/opt/mssql/data

volumes: # this volume ensures that data is persisted when the container is deleted
  sql: